### ISSUE TITLE
[BUG] Dependency still uses old group API endpoint.

### ISSUE THREAD

**Issue by pseudoprograms** [suufi/noblox.js#101]
https://devforum.roblox.com/t/official-list-of-deprecated-web-endpoints/62889/29

**Comment by pseudoprograms** [comment]
The request was being made from the old API endpoint, I replaced it with the newer one.

**Comment by suufi** [comment]
Which endpoint are you referring to?

**Comment by pseudoprograms** [comment]
> Which endpoint are you referring to?

Group API endpoint.

![](https://cdn.discordapp.com/attachments/518777797901156362/676751728695181312/unknown.png)

Here is the new one that should be used:  https://groups.roblox.com/docs#!/Membership/get_v1_groups_groupId_join_requests

**Comment by suufi** [comment]
Whoops! Looks like I forgot this one, should push out an update soon.
Thanks for the catch!
