### ISSUE TITLE
[BUG] Unhandled rejection Error: User does not exist

### ISSUE THREAD

**Issue by luke110206** [suufi/noblox.js#105]
## Before posting a bug, be sure that someone else has not posted it already and it is an actual bug with noblox.js and not other frameworks like discord.js

**Describe the bug**
I am trying to use rbx.getIdFromUsername then pushing that to getBlurb for discord verification but I get a user does not exist error. This could be because I'm not logging in but that shouldn't be needed.

**To Reproduce**
Use getIdFromUsername then feed that to getBlurb without signing in

**Expected behavior**
It gets a Id from username then uses that to get blurb form your profile

**Comment by suufi** [comment]
I can't replicate this issue so this is an issue with your code and not noblox.js. Please use the Discord server in the README for assistance.
