### ISSUE TITLE
Group wall functions/events do not work.

### ISSUE THREAD

**Issue by joritochip** [suufi/noblox.js#11]
Upon trying to use onWallPost, I am faced with this error:
`Initialization failed: You do not have permission to view the wall`

I asked Froast about it and he said that it was due to Roblox endpoint switches, and that it could be fixed but that he is no longer maintaining roblox-js.

https://cdn.discordapp.com/attachments/429453333640773638/435925845735899137/unknown.png

**Comment by EraGamer** [comment]
Edit title to say group events do not work; group functions do (`getshout`, `rank`, `promote`, etc.)
