### ISSUE TITLE
Discussion: Improving cookie login

### ISSUE THREAD

**Issue by Neztore** [suufi/noblox.js#114]
It's become clear that an improvement to the current cookie login system is required. Why?
1.  Storing a cookie in JSON on disk doesn't play nicely with services like Heroku
2.  The `cookie` file is **often** unwittingly uploaded to Github by users, putting their accounts at risk.
3.  The current system is not very customisable. You cannot adjust how often tokens are refreshed, or where they are stored.

When I originally implemented this `cookie` system I had not realised the problems that would arise with these services, or how easy it is to just commit all changes and upload them - as many users have done.

Solutions to some of these problems have been suggested in the past, in the form of PRs and issues, see: #41 , #48 and #42 .

I think this is something we need to discuss and try and find a solution for. I have a few possible suggestions:

## Suggestion 1: Do not regenerate tokens by default
This could perhaps involve providing a .regenerate method, or similar.
At present we have no idea how long cookies actually last, and so perhaps responsiblity for rotating tokens often enough should be left to the user?
This means:
- The library is once again stateless, as it should be
- A `regenerate` method, or similar, would use the current jar to generate a new one. It would then update the internally stored `jar` and return the new cookie.

I am most in favour of this solution, though it may make the library less "plug and play" for some users, the cookie file is probably the biggest source of problems.

## Suggestion 2: Make it more customisable
This would involve allowing for values like relogTime to passed, which dictates how often the token should be refreshed - or the passing of a function responsible for storing the token somewhere: Either in Disk or in a database for example. This could be documented to default to storing it in a cookie function.

-------
At any rate, I think this `cookie` behaviour needs to be more fully documented, and we should at least consider improvements even if that is made difficult by Roblox forcing us to use cookies with no guarantee as to how long they last.

**Comment by chrissie1234** [comment]
I agree with suggestion one. Making cookies able to regenerate would be awesome!

**Comment by JonasTheGamer** [comment]
Maybe also a way to "relogin". So for example you could authenticate with cookie1, then do some stuff, and then authenticate with cookie 2, do some suff, and authenticate with cookie1 again :)

**Comment by AnthonyFuller** [comment]
This could possibly be achieved using an enviroment variable and changing that. That will also help with the Heroku issue and it is safer for production.
