### ISSUE TITLE
[BUG] joinGroup() returns 301 code and fails the code.

### ISSUE THREAD

**Issue by NorteX-dev** [suufi/noblox.js#117]
**Describe the bug**
When I try using the noblox.js function "joinGroup(group)", the code fails, saying that it broke. I dug into the code a little bit and found out that the URL for joining the group (which ends with .aspx and we don't see such extensions in Roblox anymore too often) returns code 301 (Moved Permanently). I tried fixing it by finding a new URL but to no success.

**To Reproduce**
1. Use the rbx.joinGroup(000000);
2. Optional: add a .catch() to catch the error
3. 100% error occurance

**Expected behavior**
The joinGroup() function joining the group and responding with a resolved promise.

**Comment by suufi** [comment]
When you attempt to join a group on the Roblox website right now, you're forced to do a captcha due to all the bot floods through the years. That's why the endpoint hasn't been updated with noblox.js, there's no point.

**Comment by NorteX-dev** [comment]
Well, how do I cope with that problem though?

I need to join a group.
