### ISSUE TITLE
Get the status of a user such as playing a game or online

### ISSUE THREAD

**Issue by ZeRedSpy** [suufi/noblox.js#118]
## Before posting a feature request, make sure that it hasn't been suggested before, is a feasible idea, and can benefit everyone.

**Describe the solution you'd like**
I want to be able to retrieve the status such as "Playing" or "Online"

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by suufi** [comment]
This is already a thing. Please refer to the [documentation](https://noblox.js.org), it's called `getPresences`
