### ISSUE TITLE
[BUG] Cookie resets before noblox.js can change it

### ISSUE THREAD

**Issue by DroidClan** [suufi/noblox.js#121]
**Describe the bug**
Before added more commands to my program, the bot worked fine and held its cookie valid for about a week. But, after I added more content, the cookie is resetting at an astronomical rate. I've had a cookie that lasted 30 minutes, and another that lasted 3...

**Expected behavior**
I know for a fact that the cookie should not be changing this fast, and that noblox.js should be changing it before the expiration.

**Comment by suufi** [comment]
Could you please join the server found in the README to talk with you about this?
