### ISSUE TITLE
How would I accomplish using rbx.uploadItem to upload file from url?

### ISSUE THREAD

**Issue by JonasTheGamer** [suufi/noblox.js#123]
Hello,

This has been frustrating me for a while now, I've tried a lot in nodejs. The goal is to have a discord robot where I can send a command to, and I also send one attachment.

I got that part to work. The attachment is being sent as a url:
https://cdn.discordapp.com/attachments/702957372603105391/703004041050980362/Template-Shirts-R15_07262019_1.png
(for example)

However, how would I accomplish uploading this file to roblox as a shirt?

I've tried:

1. Just using fs.createReadStream(url), obviously didn't work
2. Downloading it using http get (code below, code attachment 1)
3. Opening it using Jimp (jimp.read(url) > returns a file > used that file as parameter
    Result: source.pause is not a function.

I know it is possible since I once managed to do this. However, how stupid I was not to take backups, my computer crashed so I lost the files :/ 

Code attachment 1:
```js
const noblox = require("noblox.js");
const fs = require("fs");
const http = require("https");

let attachmentURL = "https://cdn.discordapp.com/attachments/702957372603105391/703004041050980362/Template-Shirts-R15_07262019_1.png";

let assetTypeNum= 11;
let assetTitle = "Created by community";
let file = fs.createWriteStream("file.png");
    http.get(attachmentURL, response => {
      response.pipe(file);
});

let uploadid = await noblox.uploadItem(assetTitle, assetTypeNum, fs.createReadStream("file.png"))
      .then(id =>{ 
        console.log(id)
      })
```
After the execution I can see that the file actually downloaded, but that console.log always returns 11....

Thanks in advance for your assistance, I really hope we can find a way to resolve this. :-)

**Comment by JonasTheGamer** [comment]
I've just tried this:

```js
const noblox = require("noblox.js");
const fs = require("fs");
const http = require("https");

let attachmentURL = "https://cdn.discordapp.com/attachments/702957372603105391/703004041050980362/Template-Shirts-R15_07262019_1.png";

let assetTypeNum= 11;
let assetTitle = "Created by community";

http.get(attachmentURL, res => {
      noblox.uploadItem(assetTitle, assetTypeNum, fs.createWriteStream('download.png'))
      .then(id =>{ 
        console.log(id)
        message.reply(`:white_check_mark: Uploaded! Here is the link: \n :link: <https://www.roblox.com/catalog/{id}`)
      })
    });
```

But this gives me the error:
`Unhandled rejection TypeError: source.pause is not a function`

**Comment by chrissie1234** [comment]
Hey Jonas,

I've got a copy of your work, because we've collaborated on the project. 
I'm not really experienced with this function, so I couldn't explain it to the community. If you would like, you can give a short explanation for other people who are searching for a solution on this question too. 

I wish you a lot of success with your projects and stay healthy!

**Comment by JonasTheGamer** [comment]
Thanks! My old code also doesn't appear to work anymore :/ Anyways suufi asked me to close so here we go.

Explanation/help I got from him in case anyone looks this up:

> you need to download the file and readstream from it
