### ISSUE TITLE
[BUG] getRankInGroup function not working

### ISSUE THREAD

**Issue by DecodedLua** [suufi/noblox.js#124]
I'm creating a promote command and its linked with the public verify API. So it gets the Roblox id from the API. But I get an error `Unhandled rejection Error: Target user is not in group` while the user is in the group.

My code:
```
RobloxFunctions.getRankInGroup(GroupID, RobloxID).then(function(Rank){
        RobloxFunctions.promote(GroupID, RobloxID).then(function(NewRank){
             message.channel.send(ProcessingSucces)
             Client.channels.get(ClientSettings.Channels.GeneralLogs).send(ProcessingLog)
        })
})
})
```

**Comment by ConMan2102** [comment]
When ever I use this aswell I am getting the rank as 0, however, they are in the group.

**Comment by suufi** [comment]
What version of noblox.js are you running? Are you sure GroupId and RobloxID are both `Number`s? This seems to be working fine for me.

**Comment by Chosey98** [comment]
@DecodedLua @SimplyCon The GroupID and RobloxID must be Number not a string 
```
// This works
const GroupId = Number('1234123') 
const GroupId = 1231214

// This doesn't
const GroupID = '1232131'
```
