### ISSUE TITLE
[BUG] Demote/Promote backward?

### ISSUE THREAD

**Issue by SlipperySpelunky** [suufi/noblox.js#126]
## Demote/Promote backward?

**Describe the bug**
Apparently, every time I use demote or promote in the API, it goes backward. For example, if I use demote, it promotes. If I use promote, it demotes. Sometimes it may work normally. Not sure if this is my fault, but I'm guessing it's a problem with the API

**To Reproduce**
1. Simply just use demote or promote in the module.

**Expected behavior**
I expected promote to promote a person, not demote and I expected demote to demote a person, not promote.

**Comment by suufi** [comment]
This might be because of an issue that came from Roblox causing a random sort order when it came with ranks. Please update your noblox.js version to the latest version.
