### ISSUE TITLE
Role Does Not Exist [Setrank]

### ISSUE THREAD

**Issue by HydraServices** [suufi/noblox.js#131]
[Code](https://pastebin.com/ihSbi8X1)

I have used console.log()'s to see if what I'm trying to send is accurate, and it is. Everything works fine, except setrank. I'm not sure if I have misspelled something or I don't have the correct format.

I'm using version 4.5.6.

Any help would be appreciated.

**Comment by suufi** [comment]
Please refer to the [documentation](https://noblox.js.org/#set-rank) on how to properly use `setRank`. Keep in mind line 15 should be either a `Number` or a `String` depending on what you're doing.

**Comment by HydraServices** [comment]
Line 15 is a string, The command is ?setrank roblox_username rank_name

And example would be ?setrank killerbrenden Loyal Guest

This would throw an error saying that Loyal Guest doesn't exist.
