### ISSUE TITLE
[BUG] Strings don't work with SetRank but Numbers do? Rank doesn't change as well?

### ISSUE THREAD

**Issue by HydraServices** [suufi/noblox.js#132]
[Code](https://pastebin.com/ihSbi8X1)

So, I've been confused for days now on the SetRank function. I got Rank Number to work, _but it doesn't change my rank_, but it says it did. I've also tried using strings. But, it errors saying that the role does not exist. I've made sure that they are being sent as strings. I'm not sure if this is an error on my part, or ROBLOX has updated and the module needs to be updated as well.

[String Error](https://gyazo.com/886ab0ed7a557d9b5d5dd1eaadd8ff0c)

If you need anymore information, let me know I'll be glad to help!

**Comment by suufi** [comment]
That's because rank is a Number between 0 and 255. Please refer to the [documentation](https://noblox.js.org/#set-rank).
