### ISSUE TITLE
[BUG]Not logged in when logged in.

### ISSUE THREAD

**Issue by fireblast3228** [suufi/noblox.js#133]
When you use addDeveloperProduct() it always says not logged in but when I used shout without changing anything it worked perfectly fine. So I think its just addDeveloperProduct() that might be a bit bugged

**Comment by GeneralScripter** [comment]
This error can occur if the account in question does not have permission to create and edit developer products for the place, as without this permission it cannot function. The only way to achieve this at the moment is through a group game with the bot account given edit place access. With the current Team Create system, it’s not possible unless you enable the Beta Team Create permission system 10.
Either do this, or if it’s a group game then the bot will need to have edit place access in that group.

I know of two people who have had this same issue, unfortunately the API for adding developer products is quite old and gives rather ambiguous error messages.

**Comment by Neztore** [comment]
Any update on this? Is it just an issue of Roblox's errors?

If so, we can close this issue?
