### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by D9ED** [suufi/noblox.js#134]
![image](https://user-images.githubusercontent.com/24880594/82842758-bb29e200-9ea8-11ea-948f-8173905d4444.png)
Bot is now ready, nonoman#0003!
Logged in.
Unhandled rejection Error: 400 The request is invalid.

**Comment by suufi** [comment]
You are not using promises properly. See the very first section in the [documentation](https://noblox.js.org/#promises).
