### ISSUE TITLE
noblox.js.org documentation still uses deprecated function noblox.cookieLogin

### ISSUE THREAD

**Issue by IntelligentCappy** [suufi/noblox.js#137]
Noblox.js.org documentation still uses deprecated function noblox.cookieLogin, not sure if I really need to provide anything else.

**Comment by Chosey98** [comment]
Will be changed soon

**Comment by MutantRabbit767** [comment]
does anyone know how to not use it?

**Comment by suufi** [comment]
Fixed c0c69f2bb76df8f1eec0f4a3bf4c51d12fc6dbcc
