### ISSUE TITLE
[BUG] Group/post.js broken (Captcha error and unexpected token o)

### ISSUE THREAD

**Issue by IntelligentCappy** [suufi/noblox.js#138]
**Describe the bug**
group/post.js is completely broken. It first throws error "Unexpected token o in JSON" when parsing, then if you go in and just remove the JSON.parse(), you get a captcha error.

**To Reproduce**
Use the noblox.post() function.

**Expected behavior**
It should not throw any errors and post the given message to the group wall.

**Comment by Chosey98** [comment]
Create a pull request with the fix if you can and submit it

**Comment by Neztore** [comment]
Adding a wallpost now has a captcha.
This function should be removed - It is no longer possible to make a wallpost programmatically.
