### ISSUE TITLE
Using getPlayers on role with more than 100 players breaks the api.

### ISSUE THREAD

**Issue by keulerjack** [suufi/noblox.js#144]
Takes extremely long and eventually give's up with no error.

**Comment by suufi** [comment]
What device are you running `noblox.js` on? If you're using a free VPS like Glitch, you'll like run into some issues.

**Comment by ColdRBX** [comment]
I own a group with over 300 people in one roleset and frequently use noblox.js to fetch those members, therefore this is clearly an issue on your end & not with noblox.js.

**Comment by conman0552** [comment]
I've utilized this on a group with 400k members and it runs fine on the lowest rank. I'll admit it takes a long time, but on a dedicated PC or on my personal PC in a development setting it works fine. 

Again what device are you both running noblox.js on?
@keulerjack @ColdRBX

**Comment by zachariapopcorn** [comment]
I'm also getting this issue, when I try to console.log() it, it returns [AsyncFunction]

**Comment by GeneralScripter** [comment]
I find the actual behaviour of this function to be a bit odd. Other functions such as getWall return a single wall page. Why does this function have to return all players?

It's inconsistent with the rest of the functions, they provide more flexibility by being able to pass in the next cursor instead. This way you can handle how resource intensive the operation of getting all players is yourself.

**Comment by zachariapopcorn** [comment]
> I find the actual behaviour of this function to be a bit odd. Other functions such as getWall return a single wall page. Why does this function have to return all players?
> 
> It's inconsistent with the rest of the functions, they provide more flexibility by being able to pass in the next cursor instead. This way you can handle how resource intensive the operation of getting all players is yourself.

Nah, this seems much easier

**Comment by zachariapopcorn** [comment]
This is fixed now, so someone can close this
