### ISSUE TITLE
Please add these things!

### ISSUE THREAD

**Issue by MaxxieGamers** [suufi/noblox.js#15]
I have some things that i want to be added!

1. Fix joinGroup (use https://www.roblox.com/groups/join-group-ajax)

2. Add membership info at getPlayerInfo

3. Add delete InventoryItem (use https://www.roblox.com/asset/delete-from-inventory)

Thank you!

**Comment by suufi** [comment]
Seeing to this in v5

**Comment by MaxxieGamers** [comment]
when is v5 coming?

**Comment by MaxxieGamers** [comment]
Please add a function to use proxies. Because i have some users of my bot but its giving captcha after some attempts. And please at a user function to get all groups like rbx.getGroups(userid)

**Comment by sasial-roblox** [comment]
@suufi 
What is the ETA of V5 or joinGroup coming out?

**Comment by DroidClan** [comment]
Adding on, could you add a way to log the user that is performing a certain action/command?
