### ISSUE TITLE
[BUG] I am getting an error thrown from index.js which is in lib

### ISSUE THREAD

**Issue by Chosey98** [suufi/noblox.js#152]
**Describe the bug**
I am getting a warning error whenever I start the bot although it doesn't affect the bots process but it throws a warning

**To Reproduce**
Just put use noblox.js

**Expected behavior**
I didn't expect anything the warning is just being thrown but everything is fine

**Additional context**
The warning is
`Warning: Accessing non-existent property 'func' of module exports inside circular dependency`
When I used `node --trace-warnings index.js` it referred to line 22 in index.js found in lib folder
`  if (exporter.func) {` this one

**Comment by Neztore** [comment]
Hi, what is your code and version?

**Comment by Chosey98** [comment]
4.6.0 and wdym what's my code? I use more importantly setCookie() and refreshCookie() on the bot init which probably is the one triggering the warning

**Comment by Chosey98** [comment]
And getCurrentUser()

**Comment by Neztore** [comment]
What code is causing the error?
This error occurs no where else and no one else has reported it so I suspect it is related to how you are importing Noblox.

**Comment by GeneralScripter** [comment]
I'm also getting this, but only when hosting projects locally. Once they're deployed I don't see the warning. I've tested versions 4.5.4 to 4.6.1 and all seem to throw this warning when run locally, but not for the same project when deployed.

Seems to be irrespective implementation as I have tested an older project which I never saw throw the error locally or when deployed.

**Comment by Neztore** [comment]
So you only have issuing run Node v14.3?

**Comment by Chosey98** [comment]
I believe it must be a node error as I did some testing and it errors out for Node v14.x only @Neztore

**Comment by Chosey98** [comment]
Any fixes for it yet @Neztore @suufi ?

**Comment by Neztore** [comment]
Downgrade to node v12.

**Comment by Chosey98** [comment]
Alright thanks for the help
