### ISSUE TITLE
[BUG] getWall error if Guest role doesn't have permission to view

### ISSUE THREAD

**Issue by GeneralScripter** [suufi/noblox.js#154]
**Description**
When calling `rbx.getWall` with correct parameters, it will fail returning "You do not have permission to access this group wall." despite the authorised account having view wall permissions. The view group wall permission is currently required for Guests if this function is to be used without failure.

This is definitely an issue with the implementation of the request as a simple browser GET request returns the correct result.

**To reproduce**
1. Attempt `rbx.getWall` call for group with view group wall permission enabled for guests
2. Notice how it works
3. Attempt `rbx.getWall` call for group with view group wall permission disabled for guests
4. Notice how it returns an error
5. Go to group API to request from account permitted to view group wall whilst guests do not have permission
6. Notice how it works

**Expected behavior**
`rbx.getWall` returns wall posts even if "Guest" cannot view group wall so long as currently authorised account has view group wall permission.

**Comment by conman0552** [comment]
Not sure if this assists with anything, but 
![image](https://user-images.githubusercontent.com/24281023/87229541-6665fc00-c36e-11ea-9aeb-b3a157e07cba.png)

is what I am seeing if I log this. Might mean that its not properly passing the cookie?

**Comment by conman0552** [comment]
This issue is resolved in here: https://github.com/suufi/noblox.js/pull/157

args.jar was missing from the function, so it seems not all the data was being passed.

**Comment by GeneralScripter** [comment]
> args.jar was missing from the function, so it seems not all the data was being passed.

I don't know how I didn't see that before, but after passing it, it worked perfectly! Good catch.
