### ISSUE TITLE
[BUG] onJoinRequestHandle() causes X-CSRF-TOKEN error

### ISSUE THREAD

**Issue by amazman** [suufi/noblox.js#165]
**Describe the bug**
trying to use onJoinRequestHandle() causes X-CSRF-TOKEN error

**To Reproduce**
roblox.onJoinRequestHandle(00000).on('data', async request => {
    console.log(request)
});

**Expected behavior**
Print the request

**Screenshots**
https://i.imgur.com/H2oge8A.png

**Additional context**
i found it finally

**Comment by conman0552** [comment]
What is the version of noblox that you are using. 4.6.3 should resolve this issue.

To check what version, navigate to node_modules, find the noblox.js module and open the package.json file within there. The version should say it's 4.6.3. If it doesn't say this, update noblox.

**Comment by Neztore** [comment]
Or just check your package.json, or `npm list <package name>`, in this case `npm list noblox.js`.
Easiest solution: `npm install noblox.js@latest`

**Comment by amazman** [comment]
@Neztore @conman0552 im using 4.6.3 all of my other functions work such as promote, demote, and exile work perfectly fine but not this function.

https://i.imgur.com/iILF5XR.png

**Comment by JonasTheGamer** [comment]
@amazman You closed this issue, did you find a solution for this problem?

**Comment by hackhack6776** [comment]
I am having this problem somebody please help!

**Comment by Creeper-pixel** [comment]
same
