### ISSUE TITLE
[BUG] getRoles causes Unhandled rejection SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by policetonyR** [suufi/noblox.js#167]
Using setRank function in noblox.js-server (nobloxjs is up to date) causes a "Unhandled rejection SyntaxError: Unexpected token < in JSON at position 0" error. 

I made a janky fix by inserting the following code

`if (body.includes('Bad Request - Invalid URL')) return;`

With this fix, it still ranks them but with no error.

**Comment by Neztore** [comment]
Hi, not sure what you mean here.
What you describe is a bug in Noblox.js-server, from what I gather. Not Noblox.js
Please open an issue on their repo!

**Comment by policetonyR** [comment]
the problem is that the noblox.js library errors, not the server.

**Comment by Neztore** [comment]
Okay. I've just tested this method and I am having no issues - what parameters are you passing to it?

**Comment by policetonyR** [comment]
If you start a noblox.js server and try to run setrank in game it will work but error in the console.

**Comment by Neztore** [comment]
Could you please add a console.log or similar and see what the server is actually passing to the method?

**Comment by policetonyR** [comment]
![image](https://user-images.githubusercontent.com/31581859/88914631-e62a0c80-d230-11ea-9170-5d3822acfdd7.png)

S means what its sending, R is what its receiving. For some reason it is receiving the roles.

**Comment by policetonyR** [comment]
I was able to find the cause of the issue
