### ISSUE TITLE
TypeError: promise.timeout is not a function

### ISSUE THREAD

**Issue by moo1210** [suufi/noblox.js#172]
**Describe the bug**
Using an onWallPost event causes an TypeError: promise.timeout is not a function error, I am running node.js v14.5.0 if thats causing it.
**To Reproduce**
1. Run this code
`const noblox = require('noblox.js');
const fliters = [{name:"example",regex:/.*example.*/}]
const groupid = "[REDACTED]"

async function run() {
  await noblox.setCookie('[REDACTED]');
  var onWallPost = noblox.onWallPost(groupid);
  onWallPost.on('data', async function(post) {
    console.log(post.content)
    fliters.forEach(async function(item){
        if (item.regex.test(post.content)) {
          noblox.deleteWallPost(groupid, post.id)
          await noblox.follow(post.author.id)
          await noblox.message(post.author.id,`Regarding your recent post on the [REDACTED] group wall','Hey there! Sorry to let you know but your recent post on the [REDACTED] Group wall has been automatically deleted due to being catched by one of are filters. If you feel this is in error please let [REDACTED] know with all the info below.\n Post infomation \n Deleted post ID: ${post.id} \n Filter name: ${item.name}`)
          await noblox.unfollow(post.author.id)
        }
    })
  })
  onWallPost.on('error', function (err) {
    console.error(err.stack);
  });
}

run();`

**Expected behavior**
That it would run as normally

**Comment by Neztore** [comment]
This is because Bluebird isn't imported - I think several of the events have this issue.
I'll open a PR to resolve this & the others later today.
