### ISSUE TITLE
Unhandled rejection Error: Cannot get CSRF: You are not logged in. [BUG]

### ISSUE THREAD

**Issue by wowJoao** [suufi/noblox.js#174]
## Before posting a bug, be sure that someone else has not posted it already and it is an actual bug with noblox.js and not other frameworks like discord.js

This bug doesn't rank people, and instead delivers this error: Unhandled rejection Error: Cannot get CSRF: You are not logged in. - The token works fine and did not even expire, I've even tested it. I've updated Noblox to 4.6.5 too, nothing works.

Please help me out here.

**Comment by wowJoao** [comment]
The bot has all permissions.

**Comment by Neztore** [comment]
Hi! I've noticed that you've cleared the bug template provided. This template is there for a reason.
What is your code?

**Comment by wowJoao** [comment]
Which file do you need?

**Comment by wowJoao** [comment]
Nevermind, thank you.
