### ISSUE TITLE
[BUG] Promise response not expected ;(

### ISSUE THREAD

**Issue by Vylux** [suufi/noblox.js#176]
## Before posting a bug, be sure that someone else has not posted it already and it is an actual bug with noblox.js and not other frameworks like discord.js

**Describe the bug**
When i try to get player information / blurb / status, etc 

**To Reproduce**
1. Try to get a player information

**Expected behavior**
Return player information / blurb / status

**Screenshots**
![image](https://user-images.githubusercontent.com/55661836/89136658-2f1ce200-d50b-11ea-8fa9-023d2dbef937.png)

**Additional context**
_Promise [Object] {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined,
  _cancellationParent: Promise [Object] {
    _bitField: 1,
    _fulfillmentHandler0: [Function],
    _rejectionHandler0: undefined,
    _promise0: [Circular],
    _receiver0: undefined,
    _cancellationParent: Promise [Object] {
      _bitField: 1,
      _fulfillmentHandler0: [Function],
      _rejectionHandler0: undefined,
      _promise0: [Circular],
      _receiver0: undefined,
      _onCancelField: [Function],
      _branchesRemainingToCancel: 1
    },
    _branchesRemainingToCancel: 1
  }
_

**Comment by Vylux** [comment]
Fixed

**Comment by pedrotswx** [comment]
https://github.com/sentanos/roblox-js/issues/36
