### ISSUE TITLE
[BUG] refreshCookie is causing "Failed to Refresh - Invalid or expired cookie" error

### ISSUE THREAD

**Issue by policetonyR** [suufi/noblox.js#182]
**Describe the bug**
When using function refreshCookie it errors with "Failed to Refresh - Invalid or expired cookie"

**To Reproduce**
use the function refreshCookie

**Expected behavior**
returns a new cookie

**Screenshots**

![image](https://user-images.githubusercontent.com/31581859/91192883-76d6f980-e6c4-11ea-83ff-d1dd0e320b33.png)

**Comment by TorrenTamm** [comment]
Having the same error, starting from today.

**Comment by godzillafireboss** [comment]
Experiencing the same issue at the moment.
