### ISSUE TITLE
Suggestion, Examples.

### ISSUE THREAD

**Issue by The-Administrator331** [suufi/noblox.js#191]
I would like to see on web or on git hub some examples on what how to use so anyone who has little - no experience can get used to promises and how they work. Like for example for setRank how to get a role name from it. (roblox = noblox.js)
```js
roblox.setRank(groupId, userId, rankIdentifier)
.then(function(newRole){
message.channel.send(`User's rank has been changed to ${newRole.name}!`)
```

That was just an example what you could add. I just thing it could help not only me but many other people. I'm getting issue when I'm trying to get all roblox group rank's it always return's undefined or some array that I don't know how to resolve. I know it might seem simple to some nerds out there but for new people to arrays and promises its kinda rough. And the page that is about promises I can't really understand because I'm not native in English. I'm trying my best to understand it, but sometimes small help like some examples on how to use something. It could help a lot I think. I don't know how to resolve the getRoles array and that's all I can't for now. I'd appreciate if someone could help me with the code. I have been for the past...... 3? hours trying to resolve the getRoles array because I couldn't get to know why it shows undefined or an array of thing's that I can't use since if I try to use it, it just says that it isn't defined.

**Comment by Neztore** [comment]
We have examples and information on how to use Promises on our site [here](https://noblox.js.org).
The site is not completely up to date with all the latest functions, but it gives some guidance on promises and gives examples.

You can find **many** tutorials and a lot of documentation on how to use promises themselves via. a Google search. They're an integral part of JavaScript, not just this library.

If you need help using the library, I suggest you [join the RobloxAPI](https://discord.gg/EDXNdAT) discord. There are lots of helpful people there who would be happy to help.

Cheers.
