### ISSUE TITLE
[BUG] Unable to fetch group shout to discord

### ISSUE THREAD

**Issue by JUGisMUG** [suufi/noblox.js#210]
So, I was adding a new feature of whenever someone posts something on the group wall, first It didn't even fetch anything from the group wall to disocrd, I checked my code and it was correct, then for a small test, I removed the **onShout** event and just tried to get the group shout first and then send it, this is how I tried to get it fetched:
```await roblox.getShout(groupID)```
with all the important variables defined, the cookieLogin was set up aswell. And the bot sends this: 
![20201028_214423](https://user-images.githubusercontent.com/70059840/97468178-cd7fde80-1966-11eb-8d1d-fc15db0f20ff.jpg)
I then tried to remove the message embed, including removing the await promise for a test, and the bot sends this: 
![20201028_214639](https://user-images.githubusercontent.com/70059840/97468424-146dd400-1967-11eb-9624-b0bf7033d3cf.jpg)
After seeing these undefined objects there, I decided to see the noblox.js and discord.js documents for help alot of times, but my code was correct.
**The reason I think this could be happening is that noblox.js uses request, and request-promise for fetching and promise handling I assume, they both are deprecated** I realized that after looking at the npm documents for noblox.js. Is there any other way I could possibly do this, or I have to wait untill the developers of noblox.js fix the bug.

- Thanks!

**Comment by GeneralScripter** [comment]
I've just tried this out and it's working as intended for me. I believe this might be an implementation error of yours.
![Code_msZZV5imst](https://user-images.githubusercontent.com/54756166/97623502-a801dc00-1a1d-11eb-9afe-3303559c1338.png)
As you can see here, it is logging the shout details as expected. You are probably trying to pass this object directly to the Discord embed. Instead, pass in the `body` property of it instead. Noblox.js will return an object with all the properties of a group shout with the body, user, timestamp etc..

Discord clearly doesn't display JavaScript objects in a format in which you can read the contents of them. Promises are also objects, hence why putting the promise in the embed gave you that result.
