### ISSUE TITLE
Noblox cookie invalid

### ISSUE THREAD

**Issue by AGR2006** [suufi/noblox.js#216]
So what im trying to do is make a discord bot that pays people with a command. In my main code i set the cookie and in my code that is used to login, i used the nbx.cookielogin feature. It keeps saying that my cookie is invalid when i just made it.
If anyone would like to help me, please friend me on discord (AGR#2073) and i will be grateful

**Comment by BillyH-0167** [comment]
You must use setCookie not cookieLogin
