### ISSUE TITLE
Login function is rarely successful

### ISSUE THREAD

**Issue by CherryLeaves** [suufi/noblox.js#23]
Using this code, 9/10 times I receive "Token Validation Failed". It is very annoying and I can't seem to find a way around it(even using jar).

`
var rbx = require('noblox.js')
rbx.login("Username","Password")
.then(function(){
	console.log(":)")
})
.catch(function(err) {	
	console.log(err)
})
`

**Comment by sentanos** [comment]
I'm not sure why this would happen so often because of how tokens work. Regardless, I've submitted a pull request that should fix this. It would be good for someone else to look into finding the root problem.
