### ISSUE TITLE
[BUG] noblox.getRankInGroup returns error of TypeError:bodyObject.filter is not a function in some cases

### ISSUE THREAD

**Issue by ItzRock** [suufi/noblox.js#232]
**Describe the bug**
I'm trying to make a function that returns true or false corresponding if to the player id given is in a group. however, it seems it returns an error of `TypeError:bodyObject.filter is not a function` and I already deemed this not to be caused by a fault of my own (i think)

**To Reproduce**
1. Create a function with arguments of group id and player id
2. return get player in group with a .then which returns if the rank id == 0
3. receive an error
exact error i get
`TypeError: bodyObject.filter is not a function
    at c:\Users\Anthony\Desktop\noblox testi\node_modules\noblox.js\lib\group\getRankInGroup.js:20:36`

I explained that very poorly but here is an example script 

let functions = {}
functions.isInGroup = function(groupID, playerID){
    return require('noblox.js').getRankInGroup(groupID, playerID).then(i => {
        return i !== 0;
    })
}
console.log(functions.isInGroup(66997500, 7291247))

**Expected behavior**
return group id which inturns my function returns a true or false

**Screenshots**
[https://imgur.com/a/gnPpTWS](https://imgur.com/a/gnPpTWS)

**Comment by ItzRock** [comment]
Roblox issue. as it some what works with a different group (which I should have done in the first place) although is incorrect. may reopen if continues tomorrow as the Roblox servers were having issues a few hours ago

**Comment by ItzRock** [comment]
been about 11 hours and I am still having the issue, it likes to work on some groups and some users while on others it just spits out the error

**Comment by efewqefwfd** [comment]
Please make sure you are on the most recent version of noblox. There's not code on line 20 in getRankInGroup in the most recent version. 

https://github.com/suufi/noblox.js/blob/b58e72f2d48056d76ff1db99a54374220b8ade58/lib/group/getRankInGroup.js#L20

**Comment by ItzRock** [comment]
> Please make sure you are on the most recent version of noblox. There's not code on line 20 in getRankInGroup in the most recent version.
> 
> https://github.com/suufi/noblox.js/blob/b58e72f2d48056d76ff1db99a54374220b8ade58/lib/group/getRankInGroup.js#L20

bizarre, I just tried to update noblox and still I get the same error.

**Comment by ItzRock** [comment]
i just manually updated it and now its working
