### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by brandoge91** [suufi/noblox.js#236]
## Before posting a bug, be sure that someone else has not posted it already and it is an actual bug with noblox.js and not other frameworks like discord.js

**Describe the bug**
It gives me the error `cookie.toLowerCase is not a function` in the console when trying to log in with a cookie it gets from a database.
**To Reproduce**
-use a command to set a cookie variable to a database (EG: db.set("cookie", cookievar))
-do const cookietologinwith = db.get("cookie")
-do noblox.setcookie(cookietologinwith) in a function that logs the bot in
-sit back and watch the error roll in

**Expected behavior**
It logs in with the cookie provided from the database.

**Screenshots**
error: https://prnt.sc/vzcvac
setting the cookie code: https://prnt.sc/vzcvtb
getting the cookie and loggin in code: https://prnt.sc/vzcw63

**Additional context**
I am using keyv and keyv/sqlite for my database

**Comment by Neztore** [comment]
keyv returns a promise. Have you tried... logging the value of the cookie variable?

Google `NodeJS promises` or read the docs for keyv for more information... this is not a noblox bug.
Source: https://discordjs.guide/keyv/#usage has the keyword `await`, so it returns promises.
