### ISSUE TITLE
[BUG] Wiki false information: handleJoinRequest

### ISSUE THREAD

**Issue by ChrisvanChip** [suufi/noblox.js#244]
The wiki shows that [handleJoinRequest](https://github.com/suufi/noblox.js/wiki/Group-Functions#handlejoinrequest) needs username as argument, although this is not true, according to [this line of code](https://github.com/suufi/noblox.js/blob/master/lib/group/handleJoinRequest.js#L15). The wiki is not able to be contributed to directly, according to the fact the "edit" button is not present.

Reproduction is not applicable to this issue.

**Comment by ChrisvanChip** [comment]
I'd apologize, I was not aware of the new documentation website available at [noblox.js.org](https://noblox.js.org/). Would it be possible to show that on all wiki pages?

**Comment by suufi** [comment]
The wiki now has a sidebar that tells people to go to noblox.js.org instead. Thank you for the reminder! 😄
