### ISSUE TITLE
Switch up noblox.follow() API to different ROBLOX API

### ISSUE THREAD

**Issue by Wretchedjungle** [suufi/noblox.js#258]
I'm basically using the noblox.js package to run a bot that follows new followers of mine.

I'm making a small suggestion to change the noblox.follow() API endpoint to the old following API that Roblox used in games. Due to recent changes to the follow API, you can now only follow 5 every 20-30 minutes. The API endpoint I'm suggesting is now way more affective than the one noblox uses - it is capable for following up to 50 users and has a cooldown of about 30 minutes.

This change can be easily done by modifying the noblox.follow() URI from api.roblox.com/v1/users/${userId}/follow to api.roblox.com/user/follow?followedUserId=${userId}

With best wishes,
Wretchedjungle

**Comment by suufi** [comment]
That endpoint is soon to be deprecated as stated by Roblox [here](https://devforum.roblox.com/t/official-list-of-deprecated-web-endpoints/62889/38?u=qxest).

Roblox will likely continue adding arbitrary rate limits to combat bots. There's not much we can do here other than advocate for the proper implementation of a developer API.
