### ISSUE TITLE
[RATELIMITS] Failed to validate cookie

### ISSUE THREAD

**Issue by onelilspecofapop** [suufi/noblox.js#282]
_**_Issue:_**_
Hello so i made a discord bot that checks acc info using cookies and can get a players info (using getPlayerInfo and getCurrentUser) Anyways the other day i was testing if the bot would work after using the discord bot command multiple times and after around 40 times or something it gave me an error.

**"Warning: No Roblox warning detected in provided cookie. Ensure you include the entire .ROBLOSECURITY warning.
Failed to validate cookie: Are you sure the cookie is valid?
Ensure you include the full cookie, including warning text.
(node:40) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'UserName' of undefined"**

Now this may just be me and if it is can you tell me how to prevent this, thank you

**Comment by onelilspecofapop** [comment]
ok i read some of noblox.js source and found out that https://www.roblox.com/mobileapi/userinfo
ratelimits, is there a way to avoid this

**Comment by Neztore** [comment]
You can pass `false` as the second value to `setCookie`, to disable validation.
I should note that if you are using the library for mass follow botting or similar activities, we will not assist you.

Your application should only run `setCookie` once, when it starts - or if you need to use a different account. There is no need to set it every time a command is run, unless you are changing the account in use.

**Comment by onelilspecofapop** [comment]
Thankyou
