### ISSUE TITLE
Remove usage of Promise.allSettled

### ISSUE THREAD

**Issue by Neztore** [suufi/noblox.js#283]
Was added in node v12.9.0, and it's behaviour can be easily implemented using Promise.all & Array.map
I think requiring 12.9.0 is a bit recent - we should strive to support as long as possible, within reason.

**Comment by popeeyy** [comment]
Node.js states that no one should be using anything under v10 right now for a production application, so all users are encouraged to upgrade if they are using v9 or below. However, on 2021-04-30 the only releases that are receiving maintenance are v12+. All users should be on v12 in only a couple of months, so I believe we should start utilizing the features by now and require users to use recommended versions as the old versions don't get security updates anymore.

Release schedule: https://nodejs.org/en/about/releases/

**Comment by Neztore** [comment]
Fixed in PR
