### ISSUE TITLE
[BUG] API change causes "bodyObject.filter is not a function" in getRankNameInGroup

### ISSUE THREAD

**Issue by Sh1mz** [suufi/noblox.js#293]
## Before posting a bug, be sure that someone else has not posted it already and it is an actual bug with noblox.js and not other frameworks like discord.js

**Describe the bug**
When using the getRankNameInGroup related things, you get the error `bodyObject.filter is not a function` I went to investigate the node module code and found that the API endpoint in use (//api.roblox.com/users/${userId}/groups) now returns a 404 error.

**To Reproduce**
1. Go to the API endpoint used in getRankNameInGroup.js;
2. Use someone's ID on it;
3. It is now a 404 error.

**Comment by suufi** [comment]
You're actually on an outdated version, consider updating.
