### ISSUE TITLE
Getting cookie

### ISSUE THREAD

**Issue by onelilspecofapop** [suufi/noblox.js#304]
How would i  get my .ROBLOSECURITY cookie, only know how to get csrf and auth ticket, does noblox support the conversion from auth ticket to cookie and if not would that be a feature for the future.

**Comment by Neztore** [comment]
See [our tutorial](https://noblox.js.org/tutorial-Authentication.html) on getting your authentication cookie.
Noblox is a library. Converting from auth ticket -> Cookie at the library level does not really make sense - we don't store files anywhere and only use the key that is provided via. `setCookie`.

If anything, it is easier to get a cookie than an auth ticket.
