### ISSUE TITLE
Captcha on Login

### ISSUE THREAD

**Issue by mooomaaan** [suufi/noblox.js#31]
Immediately as my bot attempts to login to ROBLOX, I get this error: 
**(node:18312) UnhandledPromiseRejectionWarning: Failed to sign in, make sure all your credentials are correct. If you know they are correct, you might have gotten a captcha. Status code: 403, message: Forbidden
(node:18312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18312) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**

I need to get past this, otherwise my bot no longer functions at all.
Could anybody help me with this

**Comment by Emilius123** [comment]
How did you fix it?
