### ISSUE TITLE
setRank function not working [BUG]

### ISSUE THREAD

**Issue by BananCZE** [suufi/noblox.js#310]
Hello,
I wanted to use noblox.js library for my group ranking bot, but sadly, I've discovered that there is an issue with your library.
The Roblox api is returning code 400 (roleset doesn't exist), this is caused because you are passing to role argument "role.ID" while it should be "role.id".
Could you please look into this or tell me what am I possibly doing anything wrong? (I'm currenctly contacting directly Roblox's API endpoint, so I don't need any assistance as I don't use noblox.js in my project anymore.)

EDIT: I don't have any steps how could you reproduce this issue, because it's just basically not working at all for me and I don't think it works for anybody else.

Thanks in advance!

**Comment by Neztore** [comment]
What code are/were you using?
Our library converts role.id to role.ID - I'm not sure actually why we do this, but it's probably to try and smooth over an API inconsistency. 
I've tested getRole & getRoles (the methods which are likely to cause the issue) and cannot reproduce.
