### ISSUE TITLE
[BUG] get friend requests function

### ISSUE THREAD

**Issue by bobthedev90368** [suufi/noblox.js#332]
The get friend requests function request turns undefined when I access it as a list. I used:

//nobloxstuff start up
//*
//*
let friendRequests = await noblox.getFriendRequests({sortOrder: "Desc", limit: 100})
console.log(friendRequests[0])
//it prints undefined even when i change desc to asc I got noblox to accept friend requests just not list the first one. I am using VSCode

**Comment by alanbixby** [comment]
[`getFriendRequests()` returns an object, containing two cursors and the data](https://noblox.js.org/global.html#getFriendRequests), you must use the `data` property of the returned object.

Either use:
````js
const friendRequests = await noblox.getFriendRequests('Desc', 100)
console.log(friendRequests.data[0])
````
or utilize object deconstructors and do:
```js
const { data: friendRequests } = await noblox.,getFriendRequests('Desc, 100)
console.log(friendRequests[0])
```

In general, if you ever get `undefined`; `console.log()` your data to see what it truly looks like, you probably are making a bad assumption.
