### ISSUE TITLE
Buying a GamePass

### ISSUE THREAD

**Issue by peracc** [suufi/noblox.js#334]
Hey everyone. 
I'm trying to buy a GamePass by username, but can't really figure out if it is even possible.
Any help would be much appreciated

**Comment by suufi** [comment]
Could you elaborate on what you mean by "buy a gamepass by username"?

**Comment by peracc** [comment]
Sure, basically I'm wondering if it is possible to buy some user's gamepass. For example, I have a username, I want to list its gamepasses and buy some of those. Again, if its possible

**Comment by suufi** [comment]
I think you should be able to do this. Read the documentation: `getInventory` would be useful. Closing this issue as it doesn't relate to the library. Use the Discord for support next time.

**Comment by peracc** [comment]
Thanks, I didn't find the discord link at first, now I found it, thanks
