### ISSUE TITLE
Group Payout doesn't seem to work

### ISSUE THREAD

**Issue by mustardfoot** [suufi/noblox.js#37]
~Nothing is put into the output, the function just doesn't run.~

EDIT: This is the error that appears when attempting to run the function:

![image](https://user-images.githubusercontent.com/29512077/50732088-03702500-1139-11e9-9c7c-8c6313da6f8d.png)

`Noblox.groupPayout(groupid,Number(firstcard.name),5,false,false)` is what I'm trying to do, but nothing is happening. Ranking players works perfectly, and this is being attempted on the owner of the group's account so permissions aren't a problem.

**Comment by EraGamer** [comment]
It's an http error.

Add this to replace the current http function inside of group payouts, try again, and tell me what shows up.

```js
  return http(httpOpt)
    .then(function (res) {
      if (res.statusCode !== 200) {
        console.log(res.StatusCode)
        throw new Error(res.statusMessage)
      }
    })
}
```

**Comment by EraGamer** [comment]
It's likely something with the information you're sending.

Log `firstcard.name` and `groupid` and make sure they're what you intend.

Also, feel free to reduce your line to: `Noblox.groupPayout(groupid,Number(firstcard.name),5)`

**Comment by mustardfoot** [comment]
I'm almost positive I'm sending the correct information, and I also just found out today that `Noblox.changeRank({group: 3288652, target: Number(args[2]), change:1})` isn't working either. The error message is: `Error: Internal error, make sure the change rank request is valid` Could the group api have been changed recently? (`Number(args[2]` = 911162137)

**Comment by mustardfoot** [comment]
Nevermind, just figured out what I was doing wrong!
