### ISSUE TITLE
Rank and Getshout doesn't work while following https://github.com/sentanos/roblox-js/wiki

### ISSUE THREAD

**Issue by sasial-roblox** [suufi/noblox.js#38]

**Comment by ipadpuppydogdude1** [comment]
Can reproduce, having the same trouble.

**Comment by ipadpuppydogdude1** [comment]
Error: Internal error, make sure the change rank request is valid

**Comment by LapinoLapidus** [comment]
Do you use the cookie for authentication, like mentioned in this repo's README?

**Comment by lordhammyrblx** [comment]
Working on a fix for both very soon. Thank you for reporting this.

**Comment by lordhammyrblx** [comment]
getShout.js and onShout.js have been fixed. Rank's are next.

**Comment by sasial-roblox** [comment]
Thanks. Have an eta for it? Also, can the number be a string? Like: rank(groupid,“3”)?

**Comment by suufi** [comment]
It could technically be a string but that implies that's the player's name.
It's an integer for a reason because it's a user's ID.

**Comment by sasial-roblox** [comment]
Sorry, I meant can the rank number be a string? The player would be an interger. It would be like:
rank(groupid,playerid.“2”)

**Comment by sasial-roblox** [comment]
@LapinoLapidus Yes.

**Comment by sasial-roblox** [comment]
Seem to be working now,
@ipadpuppydogdude1 
The fix is to add this line of code:
```
    var Username = args[1]
    var strRank = args[2]
    var Rank = Number(strRank)
```
Then, use Rank in the command
