### ISSUE TITLE
Group function "getPlayers" does not work

### ISSUE THREAD

**Issue by 1230james** [suufi/noblox.js#40]
Getting a null pointer error every time I try to use getPlayers() to fetch a list of group members.

`Cannot read property '1' of null`
`(noblox.js)\lib\group\getPlayers.js:157:62`

I tried going in and manually editing the `url` portion of `opt` on/near line 135, since Roblox updated the syntax for group page URLs, but it didn't work. Might still be something to consider, though.

**Comment by iborek** [comment]
This is due to new group web design.
I have same issue.

**Comment by lordhammyrblx** [comment]
This issue was fixed in the latest [Pull Request](https://github.com/suufi/noblox.js/pull/44).

**Comment by lordhammyrblx** [comment]
> This issue was fixed in the latest [Pull Request](https://github.com/suufi/noblox.js/pull/44).

I have now merged the request and published it. You may now update to the latest npm version of noblox.js and use getPlayers.

**Comment by starexify** [comment]
Group function, onetime payouts still work?
