### ISSUE TITLE
Custom cookie loading

### ISSUE THREAD

**Issue by cloewen8** [suufi/noblox.js#41]
I was assigned the task (by Bot Services) of making this dependency compatible with our hosting provider (Heroku). As stated in the README, "we store the cookie internally in a file, and files do not persist in Heroku." I plan to resolve this by storing the cookie in a database.

If I make a pull request to support this, which would be preferable (please add a reaction or comment)?

- **Flexibility**: I add an option to provide functions for saving and loading the cookie. ❤️ 
- **Ease-of-use**: I add an option to provide a connection url to a JDBC-compatible database (requires Java 1.7+). 🚀 
- **Both**: I could do both, whoever in that case, I'd be more inclined to provide *examples* for the save and load functions that are tailored to specific database types (MySQL, SQL Server, PostgreSQL). 👀

**Comment by Kenner-G** [comment]
lmao.
