### ISSUE TITLE
Continued Error Messages

### ISSUE THREAD

**Issue by frizjack** [suufi/noblox.js#47]
I've tried 4-5 cookies and I'm still completely stuck on the error. Full log below;

```
Bad cookie.
Configuration error page listening
```

Error replicates both on OpenShift and when started locally.

**Comment by EraGamer** [comment]
Have you removed the message part of the cookie?

`_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_`

**Comment by frizjack** [comment]
Thank you for your swift reply, I seem to be getting conflicting information however I'll try this. If it works I'll close the issue.

Many thanks

**Comment by frizjack** [comment]
With that part of the Cookie removed, I'm still getting the following

```
Stored relog failed. Trying with given.
Bad cookie.
Configuration error page listening
```

With the cookie in the "cookie" file I'm getting the following
```
Bad cookie.
Configuration error page listening
```

**Comment by brandonbayliss8** [comment]
I get same error but it is every so many hours so it would work for about 6 hours then bad cookie

**Comment by NodeWired** [comment]
Thats because ou dont ping ur app, I have had my cookie last 5 months as of now.
