### ISSUE TITLE
ConfigureAsset not working?

### ISSUE THREAD

**Issue by OutlookG** [suufi/noblox.js#49]
So I have a bot with the code:

`Roblox.configureItem(2924369398,"bbb","aaa");`

and it errors with

`Unhandled rejection Error: Error configuring item, make sure not to sell unsellable items or anything else unusual.`

yet all im editing is this model here: https://www.roblox.com/library/2924369398/aaa

**Comment by suufi** [comment]
It works fine for me and it looks like it did work.
