### ISSUE TITLE
Suggestion:

### ISSUE THREAD

**Issue by sasial-roblox** [suufi/noblox.js#50]
Add the following to the wiki so people do not open issue's about rank not working:
```
//Optional:
    var Username = args[1]
//Really Need To Add:
    var strRank = args[2]
    var Rank = Number(strRank)
```

**Comment by lordhammyrblx** [comment]
This is unnecessary as the Wiki section for setRank.js clearly states the required arguments and the type of arguments said data should be.

> Arguments
> 
> group (number)
> target (number)
> either rank (number)
> or roleset (number)
> or name (string)
