### ISSUE TITLE
Bad cookie with right cookie

### ISSUE THREAD

**Issue by chrissie1234** [suufi/noblox.js#51]
Hi there!

I use noblox.js for easier communication with Roblox. I use cookieLogin to bypass captcha, although it's not working.
I've used a catch function to receive information why this isn't working, resulting in the following:

Bad cookie.
Failed to log in: Error: You are not logged in.

The bad cookie is from util/relog.js as I've noticed. I'll appreciate a solution so I can continue my work. :smiley:

**Comment by chrissie1234** [comment]
Solved, removed cookie file and renewed the cookie in the cookieLogin.

**Comment by Tyler404** [comment]
OMG THANKS SO MUCH, IT WORKS!
