### ISSUE TITLE
Undefined group roles 

### ISSUE THREAD

**Issue by 23adom** [suufi/noblox.js#55]
Having an issue with the [ _roles.oldRole.Name_ ] and [ _roles.newRole.Name_ ], i use it in a send message format "channel.send("blah ${roles.oldRole.Name} blah")" 

Any idea how to fix this? It worked on a previous version in the past and now it's not working anymore? Has the syntax changed or something? Any help appreciated!

**Comment by suufi** [comment]
It's now `name` instead of `Name`. The change was on Roblox's endpoints.
