### ISSUE TITLE
This role doesn't exist

### ISSUE THREAD

**Issue by Diltz** [suufi/noblox.js#57]
`rbx.setRank(2601636,483090613,9)`

Says role doesn't exist
http://prntscr.com/nfsnrz

**Comment by suufi** [comment]
Try doing `rbx.setRank({ group: <groupId>, target: <userId>, rank: 9 })` instead.

**Comment by Diltz** [comment]
> Try doing `rbx.setRank({ group: <groupId>, target: <userId>, rank: 9 })` instead.

Thank you, suufi! This is works.
