### ISSUE TITLE
Still says Role Does not exist

### ISSUE THREAD

**Issue by Diltz** [suufi/noblox.js#59]
`rbx.setRank({ group: 2601636, target: Number(post["Id"]), rank: 7 }) // post["Id"] this is JSON data when post async don't mind it`

http://prntscr.com/nhp5t3

**Comment by suufi** [comment]
What version of noblox are you on?

**Comment by Diltz** [comment]
4.2.6

**Comment by Diltz** [comment]
ded

**Comment by iranathan** [comment]
Are you 100% sure that that `post['Id']` is a valid id?

**Comment by suufi** [comment]
You should be using `changeRank`, not `setRank`. `setRank` is used if you have the roleset ID from Roblox which is not the 1-255 number.

**Comment by suufi** [comment]
The command works perfectly for me. The issue you probably is have is that `post["ID"]` is not the ID of a user in your group. Please check your code for any mistakes.

**Comment by Diltz** [comment]
Nope...

1 - Request added
2 - Method is post
2.1 - Check
3 - Working proccess
4 - Pasing data
5 - Request is good
6 - Everything is good group rank checked
7 - Setting rank to 7
7.1 - Setting rank to 9

![image](https://user-images.githubusercontent.com/38502930/59558815-3215f400-9025-11e9-9b17-fcbfe2c7adee.png)

**Comment by Diltz** [comment]
I'm sorry. I'm just updated noblox ver ;w;
LoL
