### ISSUE TITLE
Ability to stay logged in on chrome but still authenticate with the bot.

### ISSUE THREAD

**Issue by chexburger** [suufi/noblox.js#61]
On line 24 of relog.js, the URL is https://www.roblox.com/authentication/signoutfromallsessionsandreauthenticate. I want this removed or changed so it doesn't sign out from every session.
I'm currently playing around with it a bit to see if I can change it to not log me out. So far no success.

**Comment by suufi** [comment]
There is no other option otherwise we would have used that. 👀 This also is not your personal library so please don't seem so demanding. If you do find something, feel free to open a pull request.

**Comment by chexburger** [comment]
I guess it did seem a little demanding. Anyhow, I found a way around it. If you take the cookie that is created by the bot, log into an alt, and overwrite the cookie with the one the bot created then reload the page, it will log you in while still remaining logged into the bot. Although if the bot crashes, it will do the sign out and reauthenticate again.
