### ISSUE TITLE
onAuditLog event

### ISSUE THREAD

**Issue by dhBxnny** [suufi/noblox.js#70]
Create an event called `.onAuditLog`, which will send a customizable message to a specified channel on Discord.
An example of how it would like is:
```js
const groupId = 'groupId_here';
const groupLogs = roblox.onAuditLog(groupId);

groupLogs.on('data', function(log) {
    let embed = new Discord.RichEmbed()
    .setColor('BLUE')
    .setDescription('A new action has been done. Here are the logs.')
    .addField('User', 'log.logger.username)
    .addField('Action Type', log.type.name)
    .addField('Action Information', 'log.body);
    bot.channels.get('1234567890').send(embed);
});
groupLogs.on('error', function(err) {
    console.log(err.stack)
});
```

**Edit:** If you create this feature, please make it easier to novice noblox.js users by giving an example on the Wiki page, at Group#functions page.

**Comment by suufi** [comment]
The problem is that audit logs aren't based on WebSockets. In order to do this, you would have to waste resources polling for audit logs. This seems like a waste of effort considering the audit logs are most likely about to be redone.
