### ISSUE TITLE
[BUG] Error in getting user rank

### ISSUE THREAD

**Issue by Diltz** [suufi/noblox.js#82]
When I trying to get user rank by id i'm getting error
![image](https://user-images.githubusercontent.com/38502930/65377023-38290a00-dcd1-11e9-9779-d628d8f1f48d.png)

I use noblox.js and needle.

Code

```
            var id = arguments[0]
            
            rbx.getUsernameFromId(id)
            .then(function(id_){
                rbx.getRankInGroup(2601636,id_)
                .then(function(rank){

                    needle.post("http://107.****.94.**:****/",`&RoleId=**********&req=*****&Id=${id}&key=f37e94f1****************************800e7545c653fb6bdf73bd69`,function(err,res){
                    })
                })
            }).catch(function(err){
                console.error(err)
            })
```

**Comment by suufi** [comment]
The issue here is that you have faulty code. `getUsernameFromId` returns the user's username, not ID (not sure why you have `id_`). `getRankInGroup` uses the UserId to return the user's rank in the group, not the username.
