### ISSUE TITLE
[BUG] 401 Authorization has been denied for this request when doing .setRank

### ISSUE THREAD

**Issue by gt-c** [suufi/noblox.js#88]
**Describe the bug**
The require('noblox.js').setRank function is returning a 401 error when I am attempting to call it. The bot is logged in successfully using the cookieLogin function.

**To Reproduce**
1. await roblox.cookieLogin('cookie');
2. roblox.setRank(5262264, 1135455567, 10)
3. Receive the following error
```
Unhandled rejection Error: 401 Authorization has been denied for this request.
    at C:\Users\user\Bot\node_modules\noblox.js\lib\group\setRank.js:34:15
```

**Expected behavior**
I expected the setRank function to change the user's rank in the group, but unfortunately it appears to be erroring. I suspect that this is not a noblox.js issue, but rather a roblox api one (as I can see the error code in the API documentation) but I was unable to find reasons that this error is caused. If there is any reason as to why this is happening that would be great!

**Comment by suufi** [comment]
This issue appears to be from your end. It might be likely that you're not logging in properly or you're being captchaed.
