### ISSUE TITLE
Document everything

### ISSUE THREAD

**Issue by suufi** [suufi/noblox.js#9]
Most everything needs documentation applied to it in JSDoc form.

**Comment by EraGamer** [comment]
I'll see if I can do this.

**Comment by cloewen8** [comment]
Does it need to be JSDoc? If not, would it be worth considering using ESDoc instead? The annotations are almost identical (main difference being events and callbacks), and they offer to measure code coverage, which should make the process of writing it easier.

Either way, I can write both styles and am interested in helping out.

**Comment by chrissie1234** [comment]
The UI of ESDoc isn't really modern. Further, it isn't compatible with mobile screens, huge overlays so you can't read and use it normal.

**Comment by cloewen8** [comment]
I have since abandoned ESDoc. **JSDoc really is the better option**. ESDoc has some great concepts behind it, it is just not maintained or supported well enough.

**Comment by conman0552** [comment]
Working on this right now. I've forked the gh-page brand and I've got side tabs set. Going to get set on documenting stuff.
