### ISSUE TITLE
[BUG] changing group ranks doesn't work

### ISSUE THREAD

**Issue by natilyy** [suufi/noblox.js#91]
roblox has recently added a new group configure page: https://devforum.roblox.com/t/introducing-configure-group/406789 (for beta testers) which is probably why the change ranks/promote/demote etc no longer works.

i have a discord bot that promotes/demotes people and all it returns is this error when i try to do so:
(node:10352) DeprecationWarning: Collection#exists: use Collection#some instead
(node:10352) DeprecationWarning: Collection#find: pass a function instead
(node:10352) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
(node:10352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

don't know if this is an issue with my code but the code has been working for a while until the other day. ty!

**Comment by suufi** [comment]
The API endpoint is still functional. The error you have given me looks like it's coming from your end. You're trying to connect to something on port 80, this isn't a noblox.js issue.
